version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    env_file:
      - ./.env.dev
  redis:
    command: redis-server
    image: redis:alpine
    env_file:
      - ./.env.dev
  celery:
    build: ./app
    command: celery -A chaos worker -l INFO
    volumes:
    - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A chaos beat -l INFO
    volumes:
    - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
volumes:
  postgres_data: