# Generated by Django 3.1.3 on 2020-11-14 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremisesAccess',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('separate_entrance', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('stairs', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('without_lifting', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesAddress',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_name', models.CharField(default='', max_length=30)),
                ('country_code', models.CharField(default='', max_length=10)),
                ('post_code', models.PositiveIntegerField()),
                ('city_name', models.CharField(max_length=30)),
                ('street', models.CharField(default='', max_length=128)),
                ('house_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesClimaticConditions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heating', models.FloatField()),
                ('humidity', models.FloatField()),
                ('condensation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesDiscountDuration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_duration', models.PositiveSmallIntegerField(choices=[(0, 'Week'), (1, 'One month'), (2, 'One and half month')], default=0)),
                ('discount_size', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesDiscountsMarkups',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_rental_period', models.ManyToManyField(related_name='discount_for_rental_duration', to='premises.PremisesDiscountDuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesOwner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_profile_uuid', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesPromises',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_policy', models.TextField()),
                ('cancellation_policy', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesRestrictionThing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thing_name', models.CharField(default='', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesReview',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('premises_review_uuid', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesSeason',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesVideo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='premises_video_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonPremisesMarkup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markup_size', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premises.premisesseason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonPremisesDiscount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_size', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premises.premisesseason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesStorageSpace',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_type', models.PositiveSmallIntegerField(choices=[(0, 'Shelf'), (1, 'Rack'), (2, 'Box')], default=0)),
                ('available_rent_duration', models.PositiveIntegerField()),
                ('rent_price', models.PositiveIntegerField()),
                ('discounts_and_markups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_and_markups', to='premises.premisesdiscountsmarkups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesMedia',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photos', models.ManyToManyField(related_name='premises_photos', to='premises.PremisesImage')),
                ('videos', models.ManyToManyField(related_name='premises_videos', to='premises.PremisesVideo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesExtraOptions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ceiling_height', models.FloatField()),
                ('animals_presence', models.BooleanField(default=False)),
                ('gas_and_smoke_detector', models.BooleanField(default=True)),
                ('climatic_conditions', models.ManyToManyField(related_name='climatic_conditions', to='premises.PremisesClimaticConditions')),
                ('premises_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premises.premisesaccess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='premisesdiscountsmarkups',
            name='season_discount_size',
            field=models.ManyToManyField(related_name='season_discount_size', to='premises.SeasonPremisesDiscount'),
        ),
        migrations.AddField(
            model_name='premisesdiscountsmarkups',
            name='season_markup_size',
            field=models.ManyToManyField(related_name='season_markup_size', to='premises.SeasonPremisesMarkup'),
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField()),
                ('rent_only_whole_premises', models.BooleanField(default=False)),
                ('booking_type', models.PositiveSmallIntegerField(choices=[(0, 'Instant booking'), (1, 'Upon request')], default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premises_address', to='premises.premisesaddress')),
                ('limitation_things', models.ManyToManyField(related_name='limitation_by_type_of_things', to='premises.PremisesRestrictionThing')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premises.premisesmedia')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premises.premisesowner')),
                ('policies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premises.premisespromises')),
                ('reviews', models.ManyToManyField(to='premises.PremisesReview')),
                ('storage_spaces', models.ManyToManyField(related_name='types_of_storage_spaces', to='premises.PremisesStorageSpace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
